[connections.snowflake]
account = "OVXRMRT-ARB93959"
user = "TERZM"
password = "Nakedgunsnowflake@-0"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true